export async function callOpenRouter(env, messages, tools = null, toolChoice = 'auto') {
    // Debug mode: return canned responses for testing
    if (env.DEBUG_MODE === 'true') {
        return getCannedResponse(tools);
    }

    const body = {
        model: 'google/gemini-3-flash-preview',
        messages: messages,
        reasoning: {
            enabled: true
        }
    };

    if (tools) {
        body.tools = tools;
        body.tool_choice = toolChoice;
    }

    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${env.OPENROUTER_API_KEY}`,
            'Content-Type': 'application/json',
            'HTTP-Referer': 'https://cuuush.com',
            'X-Title': 'Calorie Tracker'
        },
        body: JSON.stringify(body)
    });

    if (!response.ok) {
        const err = await response.text();
        throw new Error(`OpenRouter Error: ${err}`);
    }

    return await response.json();
}

function getCannedResponse(tools) {
    // Check if we're being asked to log a meal
    if (tools && tools[0]?.function?.name === 'log_meal') {
        return {
            id: 'test-response-123',
            model: 'debug-mode',
            choices: [{
                message: {
                    role: 'assistant',
                    tool_calls: [{
                        id: 'call_test',
                        type: 'function',
                        function: {
                            name: 'log_meal',
                            arguments: JSON.stringify({
                                meal_title: 'Test Meal',
                                items: [
                                    { name: 'Grilled Chicken', calories: 250, protein: 45, carbs: 0 },
                                    { name: 'Brown Rice', calories: 200, protein: 5, carbs: 40 },
                                    { name: 'Steamed Broccoli', calories: 50, protein: 4, carbs: 10 }
                                ]
                            })
                        }
                    }],
                    reasoning: 'This is a test response generated by debug mode.'
                },
                finish_reason: 'tool_calls'
            }]
        };
    }

    // Default canned response
    return {
        id: 'test-response-456',
        model: 'debug-mode',
        choices: [{
            message: {
                role: 'assistant',
                content: 'This is a debug mode response.'
            },
            finish_reason: 'stop'
        }]
    };
}
